[project]
name = "irdl"
version = "1.0.0b5"
description = "Python package to download, unpack and process impulse response datasets."
readme = "README.md"
authors = [
    { name = "Art Pelling", email = "a.pelling@tu-berlin.de" },
    { name = "Siavash Zaid", email = "siavash.zaid@campus.tu-berlin.de" },
]
requires-python = ">=3.11"
license = "MIT"
license-files = ["LICENSE", "CONTRIBUTORS.md"]
keywords = [
    "impulse response",
    "downloader",
    "head-related",
    "room",
    "acoustics",
    "benchmark",
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "h5py>=3.15.1",
    "numpydoc>=1.10.0",
    "pooch>=1.8.2",
    "pyfar>=0.7.3",
    "rich>=13.0.0",
    "typer>=0.26.7,<0.27",
    "psutil>=7.0.0",
    "sofar>=1.3.0",
    "netcdf4>=1.7.3",
    "scipy>=1.14",
]

[dependency-groups]
docs = [
    "myst-parser>=4.0.1",
    "pydata-sphinx-theme>=0.16.1",
    "sphinx>=9.0.4",
    "sphinx-copybutton>=0.5.2",
    "sphinx-design>=0.7.0",
]

lint = ["ruff==0.15.16"]

tests = ["pytest"]

dev = [
    {include-group = "docs"},
    {include-group = "lint"},
    {include-group = "tests"},
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[project.scripts]
irdl = "irdl.cli:app"


[build-system]
requires = ["uv-build>=0.11.17,<0.12"]
build-backend = "uv_build"

[tool.uv.build-backend]
source-include = ["CHANGELOG.md", "LICENSE", "README.md", "src/irdl/registry/*.json"]

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple/"
publish-url = "https://upload.pypi.org/legacy/"
explicit = true


[tool.ruff]
line-length = 120
src = ["src"]
extend-exclude = ["src/irdl/repositories.py"]  # code from pooch


[tool.ruff.format]
quote-style = "double"
docstring-code-format = true
docstring-code-line-length = 120

[tool.ruff.lint]
select = [
        "A", "ARG", "ASYNC", "B", "EXE", "FBT", "PERF", "S", "SIM", "SLOT", # code correctness & safety
        "BLE", "C90", "DTZ", "E", "F", "FURB", "INP", "PIE", "PGH", "PL", "PT", "PYI", "RSE", "RET", "RUF", "SLF", "TRY", "UP", "W",  #  sanitization
        "C", "C4", "COM", "N", "NPY", "PTH", "Q", # formatting
        "I", "ICN", "TID",  # imports
        "D", "FIX", "TD",  # docstring
        "EM", "INT", "FLY", "ISC", "G", "LOG", "T20",  # strings, logging & error messages
        # "CPY",  # preview
        ]

ignore = [
    "COM812",  # conflict with ruff formatter
    "PLR0913",  # too many arguments
    "SLF001",  # private-member-access -> TBD
    "TRY003",  # avoid long messages outside exception class
]

[tool.ruff.lint.flake8-import-conventions]
banned-from  = ["numpy", "pyfar", "sofar"]
[tool.ruff.lint.flake8-import-conventions.aliases]
numpy = "np"
pyfar = "pf"
sofar = "sf"


[tool.ruff.lint.pycodestyle]
ignore-overlong-task-comments = true
max-doc-length = 100

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = ["typer.Option"]

[tool.ruff.lint.per-file-ignores]
"docs/*" = ["INP001", "PLR0912", "C901"]
"src/irdl/cli.py" = ["FBT001", "FBT003"]
"tests/*" = ["S101"]
