name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11', '3.12', '3.13', '3.14']
    steps:
      - name: Check out a copy of the repository
        uses: actions/checkout@v6
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: List env
        run: |
          uv sync --frozen && uv pip list
      - name: Run smoke tests
        uses: artpelling/irdl/.github/actions/smoke-tests@main
        with:
          command: uv run --frozen --no-dev --exact
      #- name: Run unit tests
      #  run: uv run --frozen python -m pytest
